import { v4 as uuidv4 } from "uuid";

export const CAPPUCINO = [
  {
    id: uuidv4(),
    img: require("../img/cappuchino-1.jpg"),
    rating: 4.8,
    type: "Cappucino",
    adding: "with Chocolate",
    price: 4.53,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-2.jpg"),
    rating: 4.9,
    type: "Cappucino",
    adding: "with Oat Milk",
    price: 3.9,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-3.jpg"),
    rating: 4.5,
    type: "Cappucino",
    adding: "with Caramel",
    price: 4.2,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-4.jpg"),
    rating: 4.8,
    type: "Cappucino",
    adding: "with Vanilla",
    price: 3.0,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-5.jpg"),
    rating: 3.3,
    type: "Cappucino",
    adding: "with Hazelnut",
    price: 8.5,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-6.jpg"),
    rating: 2.8,
    type: "Cappucino",
    adding: "with Cinnamon",
    price: 6.4,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-7.jpg"),
    rating: 3.9,
    type: "Cappucino",
    adding: "with Whipped Cream",
    price: 7.6,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-8.jpg"),
    rating: 5,
    type: "Cappucino",
    adding: "with Irish Cream",
    price: 9.4,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-9.jpg"),
    rating: 3.5,
    type: "Cappucino",
    adding: "with Almond Milk",
    price: 5.7,
  },
  {
    id: uuidv4(),
    img: require("../img/cappuchino-10.jpg"),
    rating: 2.2,
    type: "Cappucino",
    adding: "with Mint",
    price: 3.5,
  },
];
